# Generated by Django 4.0.6 on 2023-11-22 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_product_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='imgfile',
            field=models.ImageField(blank=True, default=1, upload_to='products'),
            preserve_default=False,
        ),
    ]
