# Generated by Django 4.2.7 on 2023-12-02 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_product_imgfile_productwithuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='productwithuser',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
