"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path
import os, json
from django.core.exceptions import ImproperlyConfigured
import environ
import django

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

env = environ.Env()
environ.Env.read_env(BASE_DIR / '.env')

SECRET_KEY = env('SECRET_KEY')
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['3.36.174.223','jieon.shop']
STATIC_ROOT = BASE_DIR / 'static/'

SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True

#셰션 유효기간 설정
SESSION_SAVE_EVERY_REQUEST = True
SESSION_COOKIE_AGE = 3600

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'noticeBoard.apps.NoticeBoardConfig',
    'user',      ##추가
    'main.apps.MainConfig',
    'reviewBoard.apps.ReviewboardConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': env('DB_NAME'),
        'USER' : env("DB_USER"),
        'PASSWORD' : env("DB_PASSWORD"),
        'HOST' : env("DB_HOST"),
        'PORT' : '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'ko-kr'

TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = []

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

#####################################
'''
AWS_STORAGE_BUCKET_NAME = 'bucket-1bt1ip'
AWS_ACCESS_KEY_ID = 'AKIAT4VQR5C2YBTBMQ74'
AWS_SECRET_ACCESS_KEY = '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'

DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
AWS_S3_REGION_NAME = 'ap-northeast-2'
AWS_S3_CUSTOM_DOMAIN = f'bucket-1bt1ip.s3.amazonaws.com'

MEDIA_URL = f'https//bucket-1bt1ip.s3.ap-northeast-2.amazonaws.com/media/'
MEDIA_ROOT = '/media/'

'''
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


############################################

AUTH_USER_MODEL = 'user.SUser' ##추가

# 로그인 성공 시 자동으로 이동할 URL
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'  ##추가

#로깅
LOGGING = {
    'version' : 1,
    'disable_existing_loggers' : False,
    'filters' : {
        'require_debug_false':{
            '()':'django.utils.log.RequireDebugFalse',
        },
    },
    'formatters' : {
        "verbose" : {
            "format": "{levelname} {asctime} {module} {message}",
            "style" : "{",
        },
    },
    "handlers" : {
        "console" : {
            "level" : "INFO",
            "filters" : ['require_debug_false'],
            "class" : "logging.StreamHandler",
            "formatter" : "verbose",
        },
    },
    "loggers" : {
        "django" : {
            "handlers" : ["console"],
            "propogate" : True,
        },
    },
}
