# Generated by Django 4.0.3 on 2023-11-28 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_customsession'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomSession',
        ),
    ]
