# Generated by Django 4.2.7 on 2023-12-02 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_delete_customsession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suser',
            name='point',
            field=models.BigIntegerField(default=2000, verbose_name='point'),
        ),
    ]
