# Generated by Django 4.2.7 on 2023-12-02 04:00

from django.db import migrations, models
import reviewBoard.models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewBoard', '0003_comment_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='imgfile',
            field=models.ImageField(blank=True, null=True, upload_to='images', validators=[reviewBoard.models.validate_file_size, reviewBoard.models.validate_image_extension]),
        ),
    ]
